// <auto-generated />
namespace Leverager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChildSpellingProblem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChildSpellingProblem));
        
        string IMigrationMetadata.Id
        {
            get { return "201302112319435_ChildSpellingProblem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
