// <auto-generated />
namespace Leverager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ContactUs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactUs));
        
        string IMigrationMetadata.Id
        {
            get { return "201305082216374_ContactUs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
